### ISSUE TITLE
App crashes out with a Java runtime error

### ISSUE THREAD

**Issue by Tequenikality** [DavideAG/NcMonitor#2]
After the issue I opened not long ago was resolved, I ran into the app crashing instead. Here's the error from the debug log:

```
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: FATAL EXCEPTION: main
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: Process: com.example.ncmonitor, PID: 9940
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ncmonitor/com.example.ncmonitor.MainActivity}: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6680)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at com.example.ncmonitor.MainActivity.showResults(MainActivity.kt:82)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at com.example.ncmonitor.MainActivity.onCreate(MainActivity.kt:50)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
04-24 11:08:17.844 10078  9940  9940 E AndroidRuntime: 	... 11 more
```

**Comment by DavideAG** [comment]
Hi,

Can you give me more details about the version of the app that you are trying to install? Is the one of the master branch? (0.5.3)

**Comment by Tequenikality** [comment]
> Hi,
> 
> Can you give me more details about the version of the app that you are trying to install? Is the one of the master branch? (0.5.3)

I just installed the latest APK from the releases section. 0.4.0 in 2021, it says.

**Comment by DavideAG** [comment]
> > Hi,
> > 
> > Can you give me more details about the version of the app that you are trying to install? Is the one of the master branch? (0.5.3)
> 
> I just installed the latest APK from the releases section. 0.4.0 in 2021, it says. 

Ok, can you try to compile and install the version of the master? It is 0.5.3

**Comment by Tequenikality** [comment]
> > > Hi,
> > > 
> > > Can you give me more details about the version of the app that you are trying to install? Is the one of the master branch? (0.5.3)
> > 
> > I just installed the latest APK from the releases section. 0.4.0 in 2021, it says. 
> 
> Ok, can you try to compile and install the version of the master? It is 0.5.3

Hi, I've tried over the last few days to do this but it's beyond my expertise. I couldn't get it to compile because it kept coming up with different errors - it was like playing text-based whack-a-mole. I'm a Web developer, and a 1-year Linux user - composing from source isn't something I've had to do before and has never been something I'm interested in.

The only testing I can do is with the APK in your releases section and that isn't working.

**Comment by DavideAG** [comment]
Well, I released the new version.
You can try to download it from here: https://github.com/DavideAG/NcMonitor/releases/tag/v0.5.4-beta

I hope that this will fix your problems.

**Comment by Tequenikality** [comment]
> Well, I released the new version.
> You can try to download it from here: https://github.com/DavideAG/NcMonitor/releases/tag/v0.5.4-beta
> 
> I hope that this will fix your problems.

I was able to install the new v5 APK and it does mostly work. Thanks.

The only exception is that my 4tb server definitely doesn't have over a million TB free 😅 But that's not a major issue.
